### ISSUE TITLE
Work: adopt Node 26 across every runtime pin

### ISSUE THREAD

**Issue by phairow** [money-noodle/money-noodle#66]
## Outcome and scope

The Node runtime pins listed below must move together, and `tools/verify-runtime.mjs` asserts at runtime that `process.versions.node` equals `package.json` `engines.node` exactly. The original Dependabot attempts split this into fragments; their dated triage and subsequent merges/reverts below are historical evidence, not current open-PR tasks or acceptance of a coordinated upgrade.

Current pins:

- `package.json` `engines.node: "22.22.3"`
- `.nvmrc` and `.node-version`: `22.22.3`
- `apps/web/Dockerfile:2,18` and `services/platform-api/Dockerfile:2,17`: `node:22.22.3-alpine3.22` with digest pins
- `package.json` `devDependencies.@types/node: "22.19.11"`
- `.github/workflows/ci.yml:34,135` and `.github/workflows/delivery.yml:101,231` read `node-version-file: .node-version`, so they follow automatically

The outcome is one reviewed change that moves every pin to the same Node major, with all repository gates green on the exact head.

## Known blockers found while triaging the Dependabot PRs

**Corepack is gone from the Node 25+ images.** PR #36 (`services/platform-api/Dockerfile` to 26.3.0) fails the container build:

```
#15 ERROR: process "/bin/sh -c corepack enable && corepack prepare pnpm@11.24.0 --activate"
    did not complete successfully: exit code: 127
```

Both Dockerfiles depend on corepack to install pnpm (`services/platform-api/Dockerfile:5`, `apps/web/Dockerfile:6`) and both delete `/usr/local/bin/corepack` in the runtime stage (`:31` and `:33`). The pnpm install method has to change in both files before any Node 26 base image can build.

**`@types/node` 26 breaks a transitive dependency's types.** PR #34 fails `platform-api:typecheck` and `platform-api:build`:

```
node_modules/.pnpm/thread-stream@4.2.0/node_modules/thread-stream/index.d.ts:96:73 - error TS2694:
Namespace '"worker_threads"' has no exported member 'TransferListItem'.
```

`thread-stream` (reached via pino) has not caught up with the `@types/node` 26 major. This is an upstream constraint, not something to work around locally by loosening the typecheck.

**PR #35 is a red herring.** Its failure is the unrelated nx task-ordering defect tracked in #65, not anything to do with Node 26.

## What actually landed (2026-09-08)

Three Dependabot PRs moving fragments of this pin were merged with failing checks, against this ticket's recommendation to defer:

- #88 raised `@types/node` to 26.4.1. Reverted by #113.
- #35 and #36 moved both Dockerfiles to `node:26.3.0-alpine3.22`. Reverted by #114.

Both blockers recorded above were confirmed in CI rather than predicted. `platform-api:typecheck` failed on the `thread-stream` `TransferListItem` error. The container failures stayed hidden until #113 restored the gate job, because the container jobs were skipped behind it; once they ran, both failed on `corepack ... exit code: 127`.

Fixing corepack alone would not have worked. `tools/verify-runtime.mjs` asserts `process.versions.node` equals `engines.node` exactly, so a Node 26 image fails at runtime regardless of how pnpm is installed. Every pin has to move together or none of them can.

#114 added `semver-major` ignores for `@types/node` and the `node` base image to `.github/dependabot.yml`, so Dependabot no longer re-proposes these fragments. Removing those ignores is part of this ticket's coordinated change, not separate cleanup.

Separately, #116 and #117 moved both images to `node:22.22.3-alpine3.22` and #120 aligned `.node-version`, `.nvmrc` and `engines.node` to match. The pins above are updated accordingly: this ticket's coordinated move now starts from 22.22.3, not 22.22.0.

This ticket remains the separate coordinated Node-upgrade tracker outside M1 and reserves no current writing lane. `Scope-Paths: none` reflects its principal-held decision state, not an execution handoff. #71 explicitly excludes Node 26 adoption; #72's shared dependency paths serve telemetry, not delegated runtime-upgrade work. Before activating an upgrade worker, the Integration-Owner must accept one bounded coordinated upgrade, require independent compatibility evidence, and re-declare its genuine exact source scope while coordinating shared paths with their current owners. Do not split or silently hand this upgrade to #71/#72. No new dependency edge or M1 prerequisite is introduced.

## Proposed approach (not yet accepted)

Do not adopt Node 26 until `thread-stream` ships types compatible with `@types/node` 26, then move every pin in one change: `engines.node`, `.nvmrc`, `.node-version`, both Dockerfiles including new base image digests and a corepack-free pnpm install, and `@types/node` with the resulting lockfile update. Decide the pnpm install method deliberately — pinned `npm i -g pnpm@11.24.0`, the standalone installer, or a `packageManager`-driven alternative — rather than whichever removes the error fastest, and keep the digest pinning the current Dockerfiles have.

As verified on 2026-09-09, #34 is closed without merge and #35/#36 are merged; the subsequent reversions are recorded above. Preserve those dispositions as historical evidence, not instructions to reopen or close them again. A future worker must re-read their current states and record the applicable evidence without replaying completed PR operations. Any new upgrade PR operation still requires its applicable separate authority.

## Required validation

- Full `pnpm check` green, including `verify:runtime` proving the running Node matches the new `engines.node`.
- Both container builds succeed for `web` and `platform-api`.
- Confirm the new base image digests are pinned and that the runtime stage still removes the package-manager tooling it is meant to remove.
- Exact-head hosted CI evidence after authorized publication. CI is not deployment.

## Exclusions and execution boundary

Only the declared `Scope-Paths` may change, in a single named execution worktree. Excludes application and service source changes, workflow edits (the version files are read through `node-version-file`), unrelated dependency bumps, and any claim, integration, merge, provider, or deployment action. The coordinator never edits tracked files.

## Acceptance

- [ ] Every Node pin names the same version, verified by `verify:runtime` rather than by inspection
- [ ] Both Dockerfiles install pnpm 11.24.0 without corepack, on digest-pinned base images
- [ ] `platform-api` typecheck and build pass with the new `@types/node`
- [ ] Both container builds pass
- [ ] Exact-head CI evidence recorded
- [ ] #34, #35, and #36 are resolved explicitly

## Registry record

Registry-Schema-Version: 2
Parent-Plan: #2
Scope-Paths: none
Depends-On: none
Dependency-Notes: Waiting on independently evidenced type compatibility and principal acceptance of one bounded coordinated upgrade with a genuine exact execution scope. PRs #34–36 have recorded historical dispositions, not outstanding instructions to repeat their closure or merge. #65 remains related independent work, not a reason to adopt Node 26. This principal-held proposal is outside M1 and reserves no current source-writing lane.
Integration-Owner: maintainer
Reconciled-Claim-Comment-IDs: none
Claim-State: blocked
Claim-Harness: unclaimed
Claim-Run-ID: unclaimed
Claim-Agent: unclaimed
Claim-Branch: unclaimed
Claim-Host: unclaimed
Claimed-At: unclaimed
Check-In-By: unclaimed
Waiting-Since: 2026-09-07T00:06:01.968Z
Checkpoint-Evidence-Version: 1
Checkpoint-State: blocked
Checkpoint-At: 2026-09-07T00:06:01.968Z
Checkpoint-Commit: 787f43c3143012022e4f3412f2465f9775b2838c
Checkpoint-Changed-Path-Count: 0
Checkpoint-Checks-Verdict: unavailable
Checkpoint-CI-Run: unavailable
Checkpoint-CI-Commit: unavailable
Checkpoint-Security-Impact: none
Checkpoint-Tenant-Impact: none
Checkpoint-Provider-Impact: none
Checkpoint-Deployment-Impact: none
Checkpoint-Residual-Risk-Count: 1
Next-Action: Remain principal-owned Blocked until upstream compatibility is independently evidenced and the maintainer accepts one bounded coordinated upgrade; re-declare exact source scope and coordinate shared paths before any claim. Preserve and verify existing PR dispositions rather than replaying completed operations; do not route execution to #71/#72.
Blockers: Independent thread-stream/@types-node compatibility evidence and acceptance of the coordinated runtime upgrade with its exact execution scope remain outstanding. This cleanup establishes neither compatibility nor upgrade acceptance. No implementation is ready or authorized from this proposal.

**Comment by phairow** [comment]
Coordination-Write-ID: rolling-wave-readiness-66
Claim-State: blocked
Claim-Harness: unclaimed
Claim-Run-ID: unclaimed
Claim-Agent: unclaimed
Claim-Branch: unclaimed
Claim-Host: unclaimed
Claimed-At: unclaimed
Check-In-By: unclaimed
Waiting-Since: 2026-09-07T00:06:01.968Z
Checkpoint-Evidence-Version: 1
Checkpoint-State: blocked
Checkpoint-At: 2026-09-07T00:06:01.968Z
Checkpoint-Commit: 787f43c3143012022e4f3412f2465f9775b2838c
Checkpoint-Changed-Path-Count: 0
Checkpoint-Checks-Verdict: unavailable
Checkpoint-CI-Run: unavailable
Checkpoint-CI-Commit: unavailable
Checkpoint-Security-Impact: none
Checkpoint-Tenant-Impact: none
Checkpoint-Provider-Impact: none
Checkpoint-Deployment-Impact: none
Checkpoint-Residual-Risk-Count: 1
Next-Action: Remain principal-owned Blocked until upstream compatibility is independently evidenced and the maintainer accepts one bounded coordinated upgrade and the disposition of PRs #34–36; re-declare exact source scope before any claim.
Blockers: External thread-stream/@types-node compatibility and acceptance of the coordinated runtime upgrade/PR disposition are outstanding. No implementation is ready or authorized from this proposal.

## Current readiness/principal-wait checkpoint

The maintainer required all open tickets without blockers to be genuinely ready for agent work. The original body already described real upstream and decision blockers, but Proposed with Depends-On none could become a pickup candidate when unrelated registry reservations clear. Blocked makes the actual principal/external wait explicit without inventing a repository dependency. The existing proposal and technical evidence remain unchanged; no type workaround, runtime move or PR closure is accepted. Scope-Paths none means there is currently no execution/source reservation; the future pin paths remain documented in the proposal and must be re-declared for an approved execution. This issue does not block first delivery as an outcome prerequisite; overlapping existing PR paths still require their separately authorized disposition.

This is coordination metadata only. The checkpoint commit is the inspected main baseline; zero repository paths changed and no validation/CI run or external operation was performed. All impact flags are none for this metadata update, not prospective work. Historical comments and the exact existing reconciliation IDs are preserved. Every agent ownership/check-in field remains unclaimed. Waiting-Since 2026-09-07T00:06:01.968Z records this new explicit principal-held transition, not an invented historical waiting age. No deadline, expiry, takeover, cleanup or implicit approval is introduced.

Residual risk (1): the explicitly declared remaining principal/external decision has not yet been satisfied, and fresh evidence is required before any later work.

**Comment by phairow** [comment]
State: blocked
Commit: none
Next: Integration-Owner resolves the independent compatibility evidence and accepts a bounded coordinated upgrade with genuine source scope before any worker claim.
Blockers: Those existing upgrade gates remain; this is outside M1 and is not an implementation release.

Planning-only wording correction requested by the maintainer. #66 remains the separate upgrade tracker: shared Dockerfile/dependency paths do not hand Node adoption to #71/#72. #71 explicitly excludes it, and #72's dependency scope is for telemetry. Scope-Paths none means no present execution reservation, not delegated ownership. No new dependency edge is added.

Also removed the stale introductory version/open-PR framing and the instruction to close PRs already disposed of. Fresh reads show #34 closed without merge and #35/#36 merged; the existing reversion history is retained. Their recorded dispositions are evidence to verify, not operations to replay or upgrade acceptance.

Exact body readback and preservation checks passed. Label, Scope-Paths, Depends-On, claim/waiting fields, acceptance checkboxes and prior comments are unchanged. No worker, claim, source/ref/worktree, PR mutation, host/provider action, upgrade test or new CI/deployment evidence was created. Other tickets and deliberate holds remain untouched.
